# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 707a54c9a0dbf17803fbbcaff444942ea05b4fc95ea9831609ebe2bbcece45806b282b8b9745d4d98d760b6c0833715446f4d0db23143f6a8be6e4c3fe35483d

test:
  secret_key_base: ff5e3b133c73695b6d9f9d677b23c6d4899b220b849d049098bcb920306dfd3b51e0ffbfffa3313a99ff6b3062f1c2a12bb8c2b1f7a6ad316f27830759988ec8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
